<?php
/**
 * The template for displaying the settings page.
 *
 * @since 0.1.0
 * @change 0.2.0 - Added option for ignoring admins.
 *
 * @global array $options Plugin Settings array.
 *
 * @package Simply Umami
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

?>
<form method="post" action="options.php" xmlns="http://www.w3.org/1999/html">
	<?php settings_fields( 'simply_umami' ); ?>
	<table class="form-table">
		<tr>
			<th scope="row">
				<?php esc_html_e( 'Enabled', 'simply-umami' ); ?>
			</th>
			<td>
				<label for="simply_umami_enabled">
					<input type="checkbox" name="simply_umami_options[enabled]" id="simply_umami_enabled"
						value="1" <?php checked( $options['enabled'] ); ?> />
					<?php esc_html_e( 'Enable umami analytics', 'simply-umami' ); ?>
				</label>
			</td>
		</tr>

		<tr>
			<th scope="row">
				<?php esc_html_e( 'Script Url', 'simply-umami' ); ?>
			</th>
			<td>
				<input class="simply-umami-url" type="url" name="simply_umami_options[script_url]" id="simply_umami_script_url"
					value="<?php echo esc_attr( $options['script_url'] ); ?>"/>
				<p class="description">
					<?php
					echo wp_kses(
						__( 'Self-hosted: <code>https://your-domain.com/script.js</code><br>Cloud: <code>https://cloud.umami.is/script.js</code>', 'simply-umami' ),
						array(
							'br'   => array(),
							'code' => array(),
						)
					);
					?>
				</p>
			</td>
		</tr>

		<tr>
			<th scope="row">
				<?php esc_html_e( 'Website ID', 'simply-umami' ); ?>
			</th>
			<td>
				<input class="simply-umami-text"  type="text" name="simply_umami_options[website_id]" id="simply_umami_website_id"
					value="<?php echo esc_attr( $options['website_id'] ); ?>"/>
				<p class="description"><?php esc_html_e( 'The umami websiteId generated by your installation', 'simply-umami' ); ?></p>
			</td>
		</tr>
	</table>

	<div class="simply-umami-collapsed">
		<input class="toggle" id="advanced-options" type="checkbox">
		<label class="toggle-label" for="advanced-options"><?php esc_html_e( 'Advanced Options', 'simply-umami' ); ?></label>
		<div class="content">
			<table class="form-table">
				<tr>
					<th scope="row">
						<?php esc_html_e( 'Host Url', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-url" type="url" name="simply_umami_options[host_url]" id="simply_umami_host_url"
							value="<?php echo esc_attr( $options['host_url'] ); ?>"/>
						<p class="description">
						<?php
						echo wp_kses(
							__( 'The URL of the Umami instance <b>if it is different from the URL to the script.</b>', 'simply-umami' ),
							array(
								'b' => array(),
							)
						);
						?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Use Host Url', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_use_host_url">
							<input type="checkbox" name="simply_umami_options[use_host_url]" id="simply_umami_use_host_url"
								value="1" <?php checked( $options['use_host_url'] ); ?> />
							<?php
							echo wp_kses(
								__( 'Use Host Url as data target. <a href="https://umami.is/docs/tracker-configuration">More information</a>', 'simply-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Ignore Admins', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_ignore_admins">
							<input type="checkbox" name="simply_umami_options[ignore_admins]" id="simply_umami_ignore_admins"
								value="1" <?php checked( $options['ignore_admins'] ); ?> />
							<?php esc_html_e( 'Disable tracking for admin users', 'simply-umami' ); ?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Auto Tracking', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_auto_track">
							<input type="checkbox" name="simply_umami_options[auto_track]" id="simply_umami_auto_track"
								value="1" <?php checked( $options['auto_track'] ); ?> />
							<?php esc_html_e( 'Automatically track pageviews and elements with Umami event attributes', 'simply-umami' ); ?>
							<p class="description">
								<?php
								echo wp_kses(
									__( 'Track manually with <code>umami.track()</code> when disabled. See <a href="https://umami.is/docs/tracker-functions">tracker functions</a>.', 'simply-umami' ),
									array(
										'code' => array(),
										'a'    => array(
											'href' => array(),
										),
									)
								);
								?>
							</p>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Track Comment Submit', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_track_comments">
							<input type="checkbox" name="simply_umami_options[track_comments]" id="simply_umami_track_comments" value="1" <?php checked( $options['track_comments'] ); ?> />
							<?php
							echo wp_kses(
								__( 'Track Comment submits using <a href="https://umami.is/docs/track-events">events</a>', 'simply-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Do Not Track', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_do_not_track">
							<input type="checkbox" name="simply_umami_options[do_not_track]" id="simply_umami_do_not_track"
								value="1" <?php checked( $options['do_not_track'] ); ?> />
							<?php
							echo wp_kses(
								__( 'Respect visitor`s <b>Do Not Track</b> setting (supported by Umami v3)', 'simply-umami' ),
								array(
									'b' => array(),
								)
							);
							?>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Tag', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-text" type="text" name="simply_umami_options[tag]" id="simply_umami_tag"
							value="<?php echo esc_attr( $options['tag'] ); ?>"/>
						<p class="description">
							<?php
							echo wp_kses(
								__( 'Group events for A/B testing. See <a href="https://umami.is/docs/tracker-configuration">tracker configuration</a>.', 'simply-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Domains', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-text" type="text" name="simply_umami_options[domains]" id="simply_umami_domains"
							value="<?php echo esc_attr( $options['domains'] ); ?>"/>
						<p class="description">
							<?php esc_html_e( 'Comma-separated list of domains where tracking is active. Leave empty to track on all domains.', 'simply-umami' ); ?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Exclude Search Params', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_exclude_search">
							<input type="checkbox" name="simply_umami_options[exclude_search]" id="simply_umami_exclude_search"
								value="1" <?php checked( $options['exclude_search'] ); ?> />
							<?php esc_html_e( 'Exclude URL query parameters from tracked page URLs', 'simply-umami' ); ?>
							<p class="description">
								<?php esc_html_e( 'Removes ?query=string from tracked URLs. Requires Umami v3.', 'simply-umami' ); ?>
							</p>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Exclude Hash', 'simply-umami' ); ?>
					</th>
					<td>
						<label for="simply_umami_exclude_hash">
							<input type="checkbox" name="simply_umami_options[exclude_hash]" id="simply_umami_exclude_hash"
								value="1" <?php checked( $options['exclude_hash'] ); ?> />
							<?php esc_html_e( 'Exclude URL hash fragments from tracked page URLs', 'simply-umami' ); ?>
							<p class="description">
								<?php esc_html_e( 'Removes #fragment from tracked URLs. Requires Umami v3.', 'simply-umami' ); ?>
							</p>
						</label>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'Before Send Function', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-text" type="text" name="simply_umami_options[before_send]" id="simply_umami_before_send"
							value="<?php echo esc_attr( $options['before_send'] ); ?>"/>
						<p class="description">
							<?php
							echo wp_kses(
								__( '<code>window[name](type, payload)</code> returns modified data, or a falsy value to cancel. Requires Umami v3.', 'simply-umami' ),
								array(
									'code' => array(),
								)
							);
							?>
						</p>
					</td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Automatic Pageviews', 'simply-umami' ); ?></th>
					<td><label><input type="checkbox" name="simply_umami_options[auto_pageview]" id="simply_umami_auto_pageview" value="1" <?php checked( $options['auto_pageview'] ); ?> />
						<?php esc_html_e( 'Track pageviews automatically, including history navigation, while keeping automatic event tracking enabled', 'simply-umami' ); ?></label></td>
				</tr>
				<tr>
					<th scope="row"><?php esc_html_e( 'Performance Metrics', 'simply-umami' ); ?></th>
					<td><label><input type="checkbox" name="simply_umami_options[performance]" id="simply_umami_performance" value="1" <?php checked( $options['performance'] ); ?> />
						<?php esc_html_e( 'Enable Umami performance and web-vitals collection', 'simply-umami' ); ?></label></td>
				</tr>
				<tr>
					<th scope="row"><label for="simply_umami_distinct_id"><?php esc_html_e( 'Distinct ID', 'simply-umami' ); ?></label></th>
					<td><input class="simply-umami-text" type="text" name="simply_umami_options[distinct_id]" id="simply_umami_distinct_id"
						value="<?php echo esc_attr( $options['distinct_id'] ); ?>" />
						<p class="description">
							<?php esc_html_e( 'A fixed pseudonymous ID groups every visitor together. Never use patient information.', 'simply-umami' ); ?>
						</p>
						<p class="description">
							<?php esc_html_e( 'Use simply_umami_tracker_attributes or umami.identify() for visitor-specific identities.', 'simply-umami' ); ?>
						</p>
					</td>
				</tr>
				<tr>
					<th scope="row"><label for="simply_umami_fetch_credentials"><?php esc_html_e( 'Fetch Credentials', 'simply-umami' ); ?></label></th>
					<td><select name="simply_umami_options[fetch_credentials]" id="simply_umami_fetch_credentials">
						<option value="omit" <?php selected( $options['fetch_credentials'], 'omit' ); ?>><?php esc_html_e( 'Omit (recommended)', 'simply-umami' ); ?></option>
						<option value="same-origin" <?php selected( $options['fetch_credentials'], 'same-origin' ); ?>><?php esc_html_e( 'Same origin', 'simply-umami' ); ?></option>
						<option value="include" <?php selected( $options['fetch_credentials'], 'include' ); ?>><?php esc_html_e( 'Include', 'simply-umami' ); ?></option>
					</select>
					<p class="description">
						<?php esc_html_e( 'Controls browser credentials sent with tracker requests. Leave Omit unless your collector requires cookies or HTTP authentication.', 'simply-umami' ); ?>
					</p></td>
				</tr>
			</table>
		</div>
	</div>

	<div class="simply-umami-collapsed">
		<input class="toggle" id="recorder-options" type="checkbox">
		<label class="toggle-label" for="recorder-options"><?php esc_html_e( 'Heatmaps and Session Replay (Optional)', 'simply-umami' ); ?></label>
		<div class="content">
			<p class="description">
				<?php esc_html_e( 'Recorder support is off by default. Also enable heatmaps or replay in your Umami website settings.', 'simply-umami' ); ?>
			</p>
			<p class="description">
				<?php esc_html_e( 'Umami controls sampling, masking, blocking, and duration. Loading recorder.js alone does not enable server capture.', 'simply-umami' ); ?>
			</p>
			<p class="description">
				<?php esc_html_e( 'Replay captures page content and interactions. Heatmaps include full URLs.', 'simply-umami' ); ?>
				<br>
				<?php esc_html_e( 'Tracker query/hash exclusions and Before Send do not sanitize recorder payloads.', 'simply-umami' ); ?>
				<br>
				<?php esc_html_e( 'Never record pages with patient information or other sensitive data. Obtain appropriate consent first.', 'simply-umami' ); ?>
			</p>
			<table class="form-table">
				<tr><th scope="row"><?php esc_html_e( 'Load Recorder', 'simply-umami' ); ?></th>
					<td><label><input type="checkbox" name="simply_umami_options[recorder_enabled]" id="simply_umami_recorder_enabled" value="1" <?php checked( $options['recorder_enabled'] ); ?> />
						<?php esc_html_e( 'I understand the privacy implications and want to load the Umami heatmap/session replay recorder', 'simply-umami' ); ?></label></td></tr>
				<tr><th scope="row"><label for="simply_umami_recorder_url"><?php esc_html_e( 'Recorder URL', 'simply-umami' ); ?></label></th>
					<td><input class="simply-umami-url" type="url" name="simply_umami_options[recorder_url]" id="simply_umami_recorder_url"
						value="<?php echo esc_attr( $options['recorder_url'] ); ?>" />
						<p class="description">
							<?php esc_html_e( 'Blank uses recorder.js beside the tracker. Cloud: https://cloud.umami.is/recorder.js. Enter a URL for another host.', 'simply-umami' ); ?>
						</p></td></tr>
			</table>
		</div>
	</div>

	<div class="simply-umami-collapsed">
		<input class="toggle" id="api-options" type="checkbox">
		<label class="toggle-label" for="api-options"><?php esc_html_e( 'API Connection (Optional)', 'simply-umami' ); ?></label>
		<div class="content">
			<p class="description">
				<?php
				echo wp_kses(
					__( 'Dashboard API: Cloud key or self-hosted username/password. See <a href="https://umami.is/docs/api">API docs</a>.', 'simply-umami' ),
					array(
						'a' => array(
							'href' => array(),
						),
					)
				);
				?>
			</p>
			<table class="form-table">
				<tr>
					<th class="row">
						<?php esc_html_e( 'API Key', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-text" type="password" name="simply_umami_options[api_key]" id="simply_umami_api_key"
							value="<?php echo esc_attr( $options['api_key'] ); ?>" autocomplete="off"/>
						<p class="description">
							<?php
							echo wp_kses(
								__( 'For Umami Cloud: create an API key at Settings &gt; API Keys in your <a href="https://cloud.umami.is">Umami Cloud</a> dashboard.', 'simply-umami' ),
								array(
									'a' => array(
										'href' => array(),
									),
								)
							);
							?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'API Username', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-text" type="text" name="simply_umami_options[api_username]" id="simply_umami_api_username"
							value="<?php echo esc_attr( $options['api_username'] ); ?>" autocomplete="off"/>
						<p class="description">
							<?php esc_html_e( 'For self-hosted Umami: your Umami admin username.', 'simply-umami' ); ?>
						</p>
					</td>
				</tr>

				<tr>
					<th class="row">
						<?php esc_html_e( 'API Password', 'simply-umami' ); ?>
					</th>
					<td>
						<input class="simply-umami-text" type="password" name="simply_umami_options[api_password]" id="simply_umami_api_password"
							value="<?php echo esc_attr( $options['api_password'] ); ?>" autocomplete="off"/>
						<p class="description">
							<?php esc_html_e( 'For self-hosted Umami: your Umami admin password.', 'simply-umami' ); ?>
						</p>
					</td>
				</tr>
			</table>
		</div>
	</div>

	<?php submit_button(); ?>
</form>
